apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: bsi-no-default-serviceaccount
  namespace: sluetzen-cluster-set
  annotations:
    policy.open-cluster-management.io/categories: Configuration
    policy.open-cluster-management.io/controls: APP.4.4.A9
    policy.open-cluster-management.io/standards: BSI-APP.4.4
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: no-default-serviceaccount-config
          remediationAction: inform
        spec:
          object-templates:
            - objectDefinition:
                apiVersion: v1
                kind: Pod
                spec:
                  serviceAccountName: default
              complianceType: mustnothave
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
              - open-cluster-management
              - openshift-*
              - default
            include:
              - "*"
  remediationAction: inform